language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" -y
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-5 -y; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install clang-3.7 --force-yes -y; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - sudo apt-get install libunwind8-dev libicu-dev libsdl2-dev -y
  - ${CXX} --version
  - ${CC} --version
  - mkdir ~/dependency-prefix
  - export PKG_CONFIG_PATH=~/dependency-prefix/lib/pkgconfig

env:
  - BUILD_TYPE="Release" LTO=on SUGGESTIONS=off
  - BUILD_TYPE="Release" LTO=on SUGGESTIONS=on

install:
  - pushd ./dependencies/tinyxml2 && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;
  - pushd ./dependencies/glm && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;
  - pushd ./dependencies/physfs && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;

before_script:
  - cmake . -DGLM_INCLUDE_DIR=~/dependency-prefix/include -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLTO=${LTO} -DEXTRA_SUGGESTIONS=${SUGGESTIONS}

script: make -j2 && make test ARGS="-V"

os:
  - linux

