language: cpp
sudo: false

addons:
  apt:
    sources:
    - debian-sid
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - cmake
    - g++-5
    - clang-3.7
    - libicu-dev
    - libunwind8-dev
# Precise lacks SDL2, so we'll build it ourselves
#    - libsdl2-dev

compiler:
  - gcc
  - clang

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - ${CXX} --version
  - ${CC} --version
  - mkdir ~/dependency-prefix
  - export PKG_CONFIG_PATH=~/dependency-prefix/lib/pkgconfig

env:
  - BUILD_TYPE="Release" LTO=on SUGGESTIONS=off
  - BUILD_TYPE="Release" LTO=on SUGGESTIONS=on

install:
# TODO: use a packaged SDL2 instead of building our own each time
  - mkdir ./dependencies/SDL2_build && pushd ./dependencies/SDL2_build && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix ../SDL2 && make -j2 && make install && popd;
  - pushd ./dependencies/tinyxml2 && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;
  - pushd ./dependencies/glm && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;
  - pushd ./dependencies/physfs && cmake -DCMAKE_INSTALL_PREFIX=~/dependency-prefix . && make -j2 && make install && popd;

before_script:
  - cmake . -DGLM_INCLUDE_DIR=~/dependency-prefix/include -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLTO=${LTO} -DEXTRA_SUGGESTIONS=${SUGGESTIONS}

script: make -j2 && make test ARGS="-V"

os:
  - linux

